########################################################################
# Management
########################################################################
management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  cloudwatch:
    metrics:
      export:
        namespace: ${PROJECT_ID}

########################################################################
# Spring
########################################################################
spring:
  application:
    name: ${PROJECT_ID}
  jmx:
    enabled: true
  main:
    banner-mode: off
  messages:
    encoding: UTF-8
  output:
    ansi:
      enabled: detect
  jackson:
    deserialization:
      read-unknown-enum-values-using-default-value: true
  jpa:
    database-platform: ca.qc.plachanc73.demo.restws.config.hibernate.CustomPostgreSQLDialect
    database: postgresql
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        multiTenancy: SCHEMA
        jdbc:
          fetch_size: 1000
          batch_size: 1000
          lob:
            non_contextual_creation: true
        discriminator:
          ignore_explicit_for_joined: true
    hibernate:
      naming:
        physical-strategy: ca.qc.plachanc73.demo.restws.config.hibernate.CustomPhysicalNamingStrategy

  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    url: jdbc-secretsmanager:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}

logging:
  level:
    com:
      spscommerce: info
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

info:
  app:
    version: @project.version@


